### ISSUE TITLE
sportclass status with wrong default state breaks downward compatibility

### ISSUE THREAD

**Issue by stoeren** [SwimStandardHub/lenex#15]
By introducing a default value for attribute `sportclass`-status and setting it by default to `CONFIRMED` the standard has a breaking change. This attribute was introduced without a major version change and conflicts therefor and breaks the standard.

Suggestion:
Increase the version number or add a revision attribute in the Lenex object.

**Comment by PetzoldThomas** [comment]
I prefer both variants.

My suggestion: Change the LENEX version number to 3.1 so that the attribute can be expected. This solves the problem in the LENEX version of swimrankings.net and in our community version.

I would also introduce the default value NONE for the enum.

The attribute LENEX.revision is also good, it can be used later for patches and fixes without changing the version number.
